import Express, { Request, Response } from "express";
import { RateLimitRequestHandler } from "express-rate-limit";
import Pg from "pg";
import { Ca } from "@cimo/authentication/dist/src/Main.js";

// Source
import * as helperSrc from "../HelperSrc.js";
import * as database from "../Database.js";
import * as modelAgent from "../model/Agent.js";

export default class Agent {
    // Variable
    private app: Express.Express;
    private limiter: RateLimitRequestHandler;

    // Method
    private checkField = (name: string, description: string, skillName: string): string => {
        let result = "";

        if (!/^[A-Za-z0-9_ ]+$/.test(name)) {
            result = "Name: Can only contain letter, number, underscore and space.";
        }

        if (!/^[A-Za-z0-9_,. ]+$/.test(description)) {
            result = "Description: Can only contain letter, number, underscore, comma, dot and space.";
        }

        if (skillName !== "" && !/^[A-Za-z0-9_]+$/.test(skillName)) {
            result = "Skill name: Can only contain letter, number and underscore.";
        }

        return result;
    };

    private tableInsert = async (mcpSessionId: string, name: string, description: string, skillName: string): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(`INSERT INTO "${mcpSessionId}_agent" (name, description, skill_name) VALUES ($1, $2, $3);`, [name, description, skillName])
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Agent.ts - tableInsert() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    private tableUpdate = async (mcpSessionId: string, id: number, name: string, description: string, skillName: string): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(`UPDATE "${mcpSessionId}_agent" SET name = $1, description = $2, skill_name = $3 WHERE id = $4;`, [
                    name,
                    description,
                    skillName,
                    id
                ])
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Agent.ts - tableUpdate() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    private tableSelect = async (mcpSessionId: string): Promise<modelAgent.Idata[]> => {
        let resultList: modelAgent.Idata[] = [];

        if (mcpSessionId !== "") {
            resultList = await database.pool
                .query(`SELECT id, name, description, skill_name FROM "${mcpSessionId}_agent";`)
                .then((queryResult: Pg.QueryResult<modelAgent.IdataDatabaseQuery>) => {
                    const dataList: modelAgent.Idata[] = [];

                    for (let a = 0; a < queryResult.rows.length; a++) {
                        const queryRow = queryResult.rows[a];

                        dataList.push({
                            id: queryRow.id,
                            name: queryRow.name,
                            description: queryRow.description,
                            skillName: queryRow.skill_name
                        });
                    }

                    return dataList;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Agent.ts - tableSelect() - catch()", error.message);

                    return [];
                });
        }

        return resultList;
    };

    private tableDelete = async (mcpSessionId: string, id: number): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(`DELETE FROM "${mcpSessionId}_agent" WHERE id = $1;`, [id])
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Agent.ts - tableDelete() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    constructor(app: Express.Express, limiter: RateLimitRequestHandler) {
        this.app = app;
        this.limiter = limiter;
    }

    tableCreate = async (mcpSessionId: string): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(
                    `CREATE TABLE IF NOT EXISTS "${mcpSessionId}_agent" (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, description TEXT, skill_name TEXT);`
                )
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Agent.ts - tableCreate() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    api = (): void => {
        this.app.post("/api/agent-create", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];
            const body = request.body as modelAgent.IapiCreateBody;

            const name = body.name;
            const description = body.description;
            const skillName = body.skillName;

            if (typeof mcpSessionId === "string") {
                const checkMessage = this.checkField(name, description, skillName);

                if (checkMessage === "") {
                    const isSuccess = await this.tableInsert(mcpSessionId, name, description, skillName);

                    if (isSuccess) {
                        helperSrc.responseBody(JSON.stringify({ message: "Agent created successfully.", isComplete: true }), "", response, 200);
                    } else {
                        helperSrc.responseBody(JSON.stringify({ message: "Failed to create agent.", isComplete: false }), "", response, 200);
                    }
                } else {
                    helperSrc.responseBody(JSON.stringify({ message: checkMessage, isComplete: false }), "", response, 200);
                }
            } else {
                helperSrc.writeLog("Agent.ts - api() - post(/api/agent-create) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            }
        });

        this.app.post("/api/agent-update", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];
            const body = request.body as modelAgent.IapiUpdateBody;

            const id = body.id;
            const name = body.name;
            const description = body.description;
            const skillName = body.skillName;

            if (typeof mcpSessionId === "string") {
                const checkMessage = this.checkField(name, description, skillName);

                if (checkMessage === "") {
                    const isSuccess = await this.tableUpdate(mcpSessionId, id, name, description, skillName);

                    if (isSuccess) {
                        helperSrc.responseBody(JSON.stringify({ message: "Agent updated successfully.", isComplete: true }), "", response, 200);
                    } else {
                        helperSrc.responseBody(JSON.stringify({ message: "Failed to update agent.", isComplete: false }), "", response, 200);
                    }
                } else {
                    helperSrc.responseBody(JSON.stringify({ message: checkMessage, isComplete: false }), "", response, 200);
                }
            } else {
                helperSrc.writeLog("Agent.ts - api() - post(/api/agent-update) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            }
        });

        this.app.get("/api/agent-list", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];

            if (typeof mcpSessionId === "string") {
                const resultList = await this.tableSelect(mcpSessionId);

                helperSrc.responseBody(JSON.stringify(resultList), "", response, 200);
            } else {
                helperSrc.writeLog("Agent.ts - api() - get(/api/agent-list) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            }
        });

        this.app.post("/api/agent-delete", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];
            const body = request.body as modelAgent.IapiDeleteBody;

            const id = body.id;

            if (typeof mcpSessionId === "string") {
                const isDelete = await this.tableDelete(mcpSessionId, id);

                if (isDelete) {
                    helperSrc.responseBody("ok", "", response, 200);
                } else {
                    helperSrc.responseBody("ko", "", response, 200);
                }
            } else {
                helperSrc.writeLog("Agent.ts - api() - post(/api/agent-delete) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            }
        });
    };
}
