import Express, { Request, Response } from "express";
import { RateLimitRequestHandler } from "express-rate-limit";
import Pg from "pg";
import { Ca } from "@cimo/authentication/dist/src/Main.js";

// Source
import * as helperSrc from "../HelperSrc.js";
import * as database from "../Database.js";
import * as modelLlm from "../model/Llm.js";

export default class Llm {
    // Variable
    private app: Express.Express;
    private limiter: RateLimitRequestHandler;

    // Method
    private tableInsert = (id: number, name: string): Promise<boolean> => {
        return database.pool
            .query(`INSERT INTO "llm" (id, name) VALUES ($1, $2) ON CONFLICT DO NOTHING;`, [id, name])
            .then(() => {
                return true;
            })
            .catch((error: Error) => {
                helperSrc.writeLog("Llm.ts - tableInsert() - catch()", error.message);

                return false;
            });
    };

    private tableSelectList = (): Promise<modelLlm.Idata[]> => {
        return database.pool
            .query(`SELECT id, name FROM "llm";`)
            .then((queryResult: Pg.QueryResult<modelLlm.IdataDatabaseQuery>) => {
                const returnList: modelLlm.Idata[] = [];

                for (let a = 0; a < queryResult.rows.length; a++) {
                    const queryRow = queryResult.rows[a];

                    returnList.push({
                        id: queryRow.id,
                        name: queryRow.name
                    });
                }

                return returnList;
            })
            .catch((error: Error) => {
                helperSrc.writeLog("Llm.ts - tableSelectList() - catch()", error.message);

                return [];
            });
    };

    constructor(app: Express.Express, limiter: RateLimitRequestHandler) {
        this.app = app;
        this.limiter = limiter;
    }

    tableCreate = async (): Promise<boolean> => {
        let isResult = false;

        const isQuery = await database.pool
            .query(`CREATE TABLE IF NOT EXISTS "llm" (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE);`)
            .then(() => {
                return true;
            })
            .catch((error: Error) => {
                helperSrc.writeLog("Llm.ts - tableCreate() - catch()", error.message);

                return false;
            });

        if (isQuery) {
            const fileReadStream = await helperSrc.fileReadStream(`${helperSrc.PATH_ROOT}${helperSrc.PATH_FILE}fixture/dev/llm.json`);

            if (Buffer.isBuffer(fileReadStream)) {
                const llmList = JSON.parse(fileReadStream.toString()) as modelLlm.Idata[];

                if (llmList.length > 0) {
                    for (const llm of llmList) {
                        await this.tableInsert(llm.id, llm.name);
                    }

                    await database.pool
                        .query(`SELECT setval(pg_get_serial_sequence('"llm"', 'id'), (SELECT COALESCE(MAX(id), 0) + 1 FROM "llm"), false);`)
                        .catch((error: Error) => {
                            helperSrc.writeLog("Llm.ts - tableCreate() - SELECT setval() - catch()", error.message);
                        });

                    isResult = true;
                }
            }
        }

        return isResult;
    };

    api = (): void => {
        this.app.get("/api/llm-list", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];

            if (typeof mcpSessionId === "string") {
                const resultList = await this.tableSelectList();

                helperSrc.responseBody(JSON.stringify(resultList), "", response, 200);
            } else {
                helperSrc.writeLog("Llm.ts - api() - get(/api/llm-list) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            }
        });
    };
}
