import Express, { Request, Response } from "express";
import { RateLimitRequestHandler } from "express-rate-limit";
import Pg from "pg";
import { Ca } from "@cimo/authentication/dist/src/Main.js";

// Source
import * as helperSrc from "../HelperSrc.js";
import * as database from "../Database.js";
import * as modelSetting from "../model/Setting.js";

export default class Setting {
    // Variable
    private app: Express.Express;
    private limiter: RateLimitRequestHandler;

    // Method
    private checkField = (llm: modelSetting.Illm[]): string => {
        let result = "";

        for (const item of llm) {
            if (item.selected) {
                if (item.url === "") {
                    result = "Llm URL is required";
                } else if (item.apiKey === "" && item.id !== 1) {
                    result = "Llm API key is required";
                }

                break;
            }
        }

        return result;
    };

    private tableInsert = async (mcpSessionId: string, id: number, llm: modelSetting.Illm[]): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(`INSERT INTO "${mcpSessionId}_setting" (id, llm) VALUES ($1, $2::jsonb) ON CONFLICT DO NOTHING;`, [id, JSON.stringify(llm)])
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableInsert() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    private tableUpdate = async (mcpSessionId: string, id: number, llm: modelSetting.Illm[]): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(`UPDATE "${mcpSessionId}_setting" SET llm = $1::jsonb WHERE id = $2;`, [JSON.stringify(llm), id])
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableUpdate() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    private tableSelect = async (mcpSessionId: string): Promise<modelSetting.Idata> => {
        let resultObject = {} as modelSetting.Idata;

        if (mcpSessionId !== "") {
            resultObject = await database.pool
                .query(`SELECT id, llm FROM "${mcpSessionId}_setting" WHERE id = 1;`)
                .then((queryResult: Pg.QueryResult<modelSetting.IdataDatabaseQuery>) => {
                    const dataObject = {} as modelSetting.Idata;

                    if (queryResult.rows.length > 0) {
                        const queryRow = queryResult.rows[0];

                        dataObject.id = queryRow.id;
                        dataObject.llm = queryRow.llm;
                    }

                    return dataObject;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableSelect() - catch()", error.message);

                    return {} as modelSetting.Idata;
                });
        }

        return resultObject;
    };

    constructor(app: Express.Express, limiter: RateLimitRequestHandler) {
        this.app = app;
        this.limiter = limiter;
    }

    tableCreate = async (mcpSessionId: string): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            const isQuery = await database.pool
                .query(
                    `CREATE TABLE IF NOT EXISTS "${mcpSessionId}_setting" (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, llm JSONB NOT NULL);`
                )
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableCreate() - catch()", error.message);

                    return false;
                });

            if (isQuery) {
                const fileReadStream = await helperSrc.fileReadStream(`${helperSrc.PATH_ROOT}${helperSrc.PATH_FILE}fixture/dev/setting.json`);

                if (Buffer.isBuffer(fileReadStream)) {
                    const fileReadStreamContent = fileReadStream.toString();

                    const settingList = JSON.parse(fileReadStreamContent) as modelSetting.Idata[];

                    if (settingList.length > 0) {
                        for (const setting of settingList) {
                            await this.tableInsert(mcpSessionId, setting.id, setting.llm);
                        }

                        isResult = true;
                    }
                }
            }
        }

        return isResult;
    };

    api = (): void => {
        this.app.get("/api/setting-read", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];

            if (typeof mcpSessionId === "string") {
                const setting = await this.tableSelect(mcpSessionId);

                const resultObject = {
                    id: setting.id,
                    llm: setting.llm
                };

                helperSrc.responseBody(JSON.stringify(resultObject), "", response, 200);
            } else {
                helperSrc.writeLog("Setting.ts - api() - get(/api/setting-read) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            }
        });

        this.app.post("/api/setting-update", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];
            const body = request.body as modelSetting.IapiDataUpdateBody;

            const id = body.id;
            const llm = body.llm;

            if (typeof mcpSessionId === "string") {
                const message = this.checkField(llm);

                if (message === "") {
                    const isUpdate = await this.tableUpdate(mcpSessionId, id, llm);

                    if (isUpdate) {
                        helperSrc.responseBody(JSON.stringify({ status: "ok", message: "Setting updated successfully." }), "", response, 200);
                    } else {
                        helperSrc.responseBody(JSON.stringify({ status: "ko", message: "Failed to update setting." }), "", response, 200);
                    }
                } else {
                    helperSrc.responseBody(JSON.stringify({ status: "ko", message }), "", response, 200);
                }
            } else {
                helperSrc.writeLog("Setting.ts - api() - post(/api/setting-update) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            }
        });
    };
}
