import Express, { Request, Response } from "express";
import { RateLimitRequestHandler } from "express-rate-limit";
import Pg from "pg";
import { Ca } from "@cimo/authentication/dist/src/Main.js";

// Source
import * as helperSrc from "../HelperSrc.js";
import * as database from "../Database.js";
import * as modelSetting from "../model/Setting.js";

export default class Setting {
    // Variable
    private app: Express.Express;
    private limiter: RateLimitRequestHandler;

    // Method
    private checkField = (llmList: modelSetting.Illm[]): string[] => {
        const resultList: string[] = [];

        for (const llm of llmList) {
            if (llm.selected) {
                if (
                    !/^https?:\/\/(?:[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?(?::\d{1,5})?(?:\/[A-Za-z0-9._~-]+)*\/?$/.test(
                        llm.url
                    )
                ) {
                    resultList.push("Llm - Url: Can only contain a standard url format.");
                }

                if (!/^[A-Za-z0-9_-]+$/.test(llm.apiKey) && llm.id !== 1) {
                    resultList.push("Llm - Api key: Can only contain letter, number, underscore and hyphen.");
                }

                break;
            }
        }

        return resultList;
    };

    private tableInsert = async (mcpSessionId: string, id: number, llm: modelSetting.Illm[]): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(`INSERT INTO "${mcpSessionId}_setting" (id, llm) VALUES ($1, $2::jsonb) ON CONFLICT DO NOTHING;`, [id, JSON.stringify(llm)])
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableInsert() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    private tableUpdate = async (mcpSessionId: string, id: number, llm: modelSetting.Illm[]): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(`UPDATE "${mcpSessionId}_setting" SET llm = $1::jsonb WHERE id = $2;`, [JSON.stringify(llm), id])
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableUpdate() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    private tableSelect = async (mcpSessionId: string): Promise<modelSetting.Idata> => {
        let resultObject = {} as modelSetting.Idata;

        if (mcpSessionId !== "") {
            resultObject = await database.pool
                .query(`SELECT id, llm FROM "${mcpSessionId}_setting" WHERE id = 1;`)
                .then((queryResult: Pg.QueryResult<modelSetting.IdataDatabaseQuery>) => {
                    const dataObject = {} as modelSetting.Idata;

                    if (queryResult.rows.length > 0) {
                        const queryRow = queryResult.rows[0];

                        dataObject.id = queryRow.id;
                        dataObject.llm = queryRow.llm;
                    }

                    return dataObject;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableSelect() - catch()", error.message);

                    return {} as modelSetting.Idata;
                });
        }

        return resultObject;
    };

    constructor(app: Express.Express, limiter: RateLimitRequestHandler) {
        this.app = app;
        this.limiter = limiter;
    }

    tableCreate = async (mcpSessionId: string): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            const isQuery = await database.pool
                .query(
                    `CREATE TABLE IF NOT EXISTS "${mcpSessionId}_setting" (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, llm JSONB NOT NULL);`
                )
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableCreate() - catch()", error.message);

                    return false;
                });

            if (isQuery) {
                const fileReadStream = await helperSrc.fileReadStream(`${helperSrc.PATH_ROOT}${helperSrc.PATH_FILE}fixture/dev/setting.json`);

                if (Buffer.isBuffer(fileReadStream)) {
                    const fileReadStreamContent = fileReadStream.toString();

                    const settingList = JSON.parse(fileReadStreamContent) as modelSetting.Idata[];

                    if (settingList.length > 0) {
                        for (const setting of settingList) {
                            await this.tableInsert(mcpSessionId, setting.id, setting.llm);
                        }

                        isResult = true;
                    }
                }
            }
        }

        return isResult;
    };

    api = (): void => {
        this.app.get("/api/setting-read", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];

            if (typeof mcpSessionId !== "string") {
                helperSrc.writeLog("Setting.ts - api() - get(/api/setting-read) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            } else {
                const setting = await this.tableSelect(mcpSessionId);

                if (Object.keys(setting).length === 0) {
                    helperSrc.responseBody("", "ko", response, 500);
                } else {
                    helperSrc.responseBody(
                        JSON.stringify({
                            state: "ok",
                            message: "",
                            data: {
                                id: setting.id,
                                llm: setting.llm
                            }
                        }),
                        "",
                        response,
                        200
                    );
                }
            }
        });

        this.app.post("/api/setting-update", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];
            const body = request.body as modelSetting.IapiUpdateBody;

            const id = body.id;
            const llmList = body.llm;

            if (typeof mcpSessionId !== "string") {
                helperSrc.writeLog("Setting.ts - api() - post(/api/setting-update) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            } else {
                const checkMessageList = this.checkField(llmList);

                if (checkMessageList.length > 0) {
                    helperSrc.responseBody(JSON.stringify({ state: "ko", message: checkMessageList }), "", response, 200);
                } else {
                    const isTableUpdate = await this.tableUpdate(mcpSessionId, id, llmList);

                    if (!isTableUpdate) {
                        helperSrc.responseBody("", "ko", response, 500);
                    } else {
                        helperSrc.responseBody(JSON.stringify({ state: "ok", message: "Setting updated successfully." }), "", response, 200);
                    }
                }
            }
        });
    };
}
