import Express, { Request, Response } from "express";
import { RateLimitRequestHandler } from "express-rate-limit";
import Pg from "pg";
import { Ca } from "@cimo/authentication/dist/src/Main.js";

// Source
import * as helperSrc from "../HelperSrc.js";
import * as database from "../Database.js";
import * as modelSetting from "../model/Setting.js";

export default class Setting {
    // Variable
    private app: Express.Express;
    private limiter: RateLimitRequestHandler;

    // Method
    private tableInsert = async (mcpSessionId: string, id: number, apiId: number): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(`INSERT INTO "${mcpSessionId}_setting" (id, api_id) VALUES ($1, $2) ON CONFLICT DO NOTHING;`, [id, apiId])
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableInsert() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    private tableUpdate = async (mcpSessionId: string, id: number, apiId: number): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            isResult = await database.pool
                .query(`UPDATE "${mcpSessionId}_setting" SET api_id = $1 WHERE id = $2;`, [apiId, id])
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableUpdate() - catch()", error.message);

                    return false;
                });
        }

        return isResult;
    };

    private tableSelect = async (mcpSessionId: string): Promise<modelSetting.Idata> => {
        let resultObject = {} as modelSetting.Idata;

        if (mcpSessionId !== "") {
            resultObject = await database.pool
                .query(`SELECT id, api_id FROM "${mcpSessionId}_setting" WHERE id = 1;`)
                .then((queryResult: Pg.QueryResult<modelSetting.IdataDatabaseQuery>) => {
                    const dataObject = {} as modelSetting.Idata;

                    if (queryResult.rows.length > 0) {
                        const queryRow = queryResult.rows[0];

                        dataObject.id = queryRow.id;
                        dataObject.apiId = queryRow.api_id;
                    }

                    return dataObject;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableSelect() - catch()", error.message);

                    return {} as modelSetting.Idata;
                });
        }

        return resultObject;
    };

    constructor(app: Express.Express, limiter: RateLimitRequestHandler) {
        this.app = app;
        this.limiter = limiter;
    }

    tableCreate = async (mcpSessionId: string): Promise<boolean> => {
        let isResult = false;

        if (mcpSessionId !== "") {
            const isQuery = await database.pool
                .query(
                    `CREATE TABLE IF NOT EXISTS "${mcpSessionId}_setting" (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, api_id INTEGER NOT NULL);`
                )
                .then(() => {
                    return true;
                })
                .catch((error: Error) => {
                    helperSrc.writeLog("Setting.ts - tableCreate() - catch()", error.message);

                    return false;
                });

            if (isQuery) {
                const fileReadStream = await helperSrc.fileReadStream(`${helperSrc.PATH_ROOT}${helperSrc.PATH_FILE}fixture/dev/setting.json`);

                if (Buffer.isBuffer(fileReadStream)) {
                    const fileReadStreamContent = fileReadStream.toString();

                    const settingList = JSON.parse(fileReadStreamContent) as modelSetting.Idata[];

                    if (settingList.length > 0) {
                        for (const setting of settingList) {
                            await this.tableInsert(mcpSessionId, setting.id, setting.apiId);
                        }

                        isResult = true;
                    }
                }
            }
        }

        return isResult;
    };

    api = (): void => {
        this.app.get("/api/setting-info", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];

            if (typeof mcpSessionId === "string") {
                const setting = await this.tableSelect(mcpSessionId);

                const resultObject = {
                    id: setting.id,
                    apiId: setting.apiId
                };

                helperSrc.responseBody(JSON.stringify(resultObject), "", response, 200);
            } else {
                helperSrc.writeLog("Setting.ts - api() - get(/api/setting-info) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            }
        });

        this.app.post("/api/setting-update", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];
            const body = request.body as modelSetting.IapiDataUpdateBody;

            const id = body.id;
            const apiId = body.apiId;

            if (typeof mcpSessionId === "string") {
                const isUpdate = await this.tableUpdate(mcpSessionId, id, apiId);

                if (isUpdate) {
                    helperSrc.responseBody("ok", "", response, 200);
                } else {
                    helperSrc.responseBody("ko", "", response, 200);
                }
            } else {
                helperSrc.writeLog("Setting.ts - api() - post(/api/setting-update) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            }
        });
    };
}
