import Express, { Request, Response } from "express";
import { RateLimitRequestHandler } from "express-rate-limit";
import * as Crypto from "crypto";
import Pg from "pg";
import { Ca } from "@cimo/authentication/dist/src/Main.js";

// Source
import * as helperSrc from "../HelperSrc.js";
import * as database from "../Database.js";
import * as modelUser from "../model/User.js";

export default class User {
    // Variable
    private app: Express.Express;
    private limiter: RateLimitRequestHandler;

    // Method
    private passwordHash = (password: string): string => {
        const salt = Crypto.randomBytes(16).toString("hex");
        const hash = Crypto.scryptSync(password, salt, 64).toString("hex");

        return `${salt}:${hash}`;
    };

    private passwordVerify = (password: string, passwordUser: string): boolean => {
        let isResult = false;

        const passwordUserSplit = passwordUser.split(":");

        if (passwordUserSplit.length === 2) {
            const hash = Crypto.scryptSync(password, passwordUserSplit[0], 64).toString("hex");

            isResult = Crypto.timingSafeEqual(Buffer.from(hash, "hex"), Buffer.from(passwordUserSplit[1], "hex"));
        }

        return isResult;
    };

    private checkField = (name: string, surname: string): string[] => {
        const resultList: string[] = [];

        if (!/^[A-Za-z0-9_]+$/.test(name)) {
            resultList.push("Name: Can only contain letter, number and underscore.");
        }

        if (!/^[A-Za-z0-9_]+$/.test(surname)) {
            resultList.push("Surname: Can only contain letter, number and underscore.");
        }

        return resultList;
    };

    private tableInsert = (
        id: number,
        email: string,
        name: string,
        surname: string,
        password: string,
        mcpSessionId: string | null,
        isDelete: boolean
    ): Promise<boolean> => {
        const hash = password === "" ? null : this.passwordHash(password);

        return database.pool
            .query(
                `INSERT INTO "user" (id, email, name, surname, password, mcp_session_id, delete) VALUES ($1, $2, $3, $4, $5, NULLIF($6, ''), $7) ON CONFLICT DO NOTHING;`,
                [id, email, name, surname, hash, mcpSessionId, isDelete]
            )
            .then(() => {
                return true;
            })
            .catch((error: Error) => {
                helperSrc.writeLog("User.ts - tableInsert() - catch()", error.message);

                return false;
            });
    };

    private tableUpdate = (id: number, name: string, surname: string, password: string, mcpSessionId: string): Promise<boolean> => {
        const hash = password === "" ? null : this.passwordHash(password);

        return database.pool
            .query(`UPDATE "user" SET name = $1, surname = $2, password = COALESCE($3, password), mcp_session_id = NULLIF($4, '') WHERE id = $5;`, [
                name,
                surname,
                hash,
                mcpSessionId,
                id
            ])
            .then(() => {
                return true;
            })
            .catch((error: Error) => {
                helperSrc.writeLog("User.ts - tableUpdate() - catch()", error.message);

                return false;
            });
    };

    private tableSelect = (email: string, mcpSessionId: string): Promise<modelUser.Idata> => {
        return database.pool
            .query(
                `SELECT id, email, name, surname, password, mcp_session_id FROM "user" WHERE (email = $1 OR mcp_session_id = $2) AND NOT delete ORDER BY id ASC;`,
                [email, mcpSessionId]
            )
            .then((queryResult: Pg.QueryResult<modelUser.IdataDatabaseQuery>) => {
                const resultObject = {} as modelUser.Idata;

                if (queryResult.rows.length > 0) {
                    const queryRow = queryResult.rows[0];

                    resultObject.id = queryRow.id;
                    resultObject.email = queryRow.email;
                    resultObject.name = queryRow.name;
                    resultObject.surname = queryRow.surname;
                    resultObject.password = queryRow.password;
                    resultObject.mcpSessionId = queryRow.mcp_session_id;
                }

                return resultObject;
            })
            .catch((error: Error) => {
                helperSrc.writeLog("User.ts - tableSelect() - catch()", error.message);

                return {} as modelUser.Idata;
            });
    };

    constructor(app: Express.Express, limiter: RateLimitRequestHandler) {
        this.app = app;
        this.limiter = limiter;
    }

    tableCreate = async (): Promise<boolean> => {
        let isResult = false;

        const isQuery = await database.pool
            .query(
                `CREATE TABLE IF NOT EXISTS "user" (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, surname TEXT NOT NULL, password TEXT NOT NULL, mcp_session_id TEXT UNIQUE, delete BOOLEAN NOT NULL);`
            )
            .then(() => {
                return true;
            })
            .catch((error: Error) => {
                helperSrc.writeLog("User.ts - tableCreate() - catch()", error.message);

                return false;
            });

        if (isQuery) {
            const fileReadStream = await helperSrc.fileReadStream(`${helperSrc.PATH_ROOT}${helperSrc.PATH_FILE}fixture/dev/user.json`);

            if (Buffer.isBuffer(fileReadStream)) {
                const userList = JSON.parse(fileReadStream.toString()) as modelUser.Idata[];

                if (userList.length > 0) {
                    for (const user of userList) {
                        await this.tableInsert(user.id, user.email, user.name, user.surname, user.password, user.mcpSessionId, user.isDelete);
                    }

                    isResult = true;
                }
            }
        }

        return isResult;
    };

    loginSessionVerify = async (username: string, password: string): Promise<modelUser.IdataLoginSession> => {
        const resultObject = {} as modelUser.IdataLoginSession;

        if (username === "" || password === "") {
            resultObject.mcpSessionId = "";
            resultObject.message = "Please enter username and password.";
        } else {
            const user = await this.tableSelect(username, "");

            if (!user.id) {
                resultObject.mcpSessionId = "";
                resultObject.message = "Incorrect username.";
            } else {
                if (!this.passwordVerify(password, user.password)) {
                    resultObject.mcpSessionId = "";
                    resultObject.message = "Incorrect password.";
                } else {
                    if (user.mcpSessionId) {
                        resultObject.mcpSessionId = user.mcpSessionId;
                        resultObject.message = "";
                    } else {
                        resultObject.mcpSessionId = helperSrc.generateUniqueId();
                        resultObject.message = "";

                        await this.tableUpdate(user.id, user.name, user.surname, "", resultObject.mcpSessionId);
                    }
                }
            }
        }

        return resultObject;
    };

    api = (): void => {
        this.app.get("/api/user-read", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];

            if (typeof mcpSessionId !== "string") {
                helperSrc.writeLog("User.ts - api() - get(/api/user-info) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            } else {
                const user = await this.tableSelect("", mcpSessionId);

                if (Object.keys(user).length === 0) {
                    helperSrc.responseBody("", "ko", response, 500);
                } else {
                    helperSrc.responseBody(
                        JSON.stringify({
                            state: "ok",
                            message: "",
                            data: {
                                id: user.id,
                                email: user.email,
                                name: user.name,
                                surname: user.surname
                            }
                        }),
                        "",
                        response,
                        200
                    );
                }
            }
        });

        this.app.post("/api/user-update", this.limiter, Ca.authenticationMiddleware, async (request: Request, response: Response) => {
            const mcpSessionId = request.headers["mcp-session-id"];
            const body = request.body as modelUser.IapiUpdateBody;

            const id = body.id;
            const name = body.name;
            const surname = body.surname;
            const password = body.password;

            if (typeof mcpSessionId !== "string") {
                helperSrc.writeLog("User.ts - api() - post(/api/user-update) - Error", "Missing or invalid header.");

                helperSrc.responseBody("", "ko", response, 500);
            } else {
                const checkMessageList = this.checkField(name, surname);

                if (checkMessageList.length > 0) {
                    helperSrc.responseBody(JSON.stringify({ state: "ko", message: checkMessageList }), "", response, 200);
                } else {
                    const isTableUpdate = await this.tableUpdate(id, name, surname, password, mcpSessionId);

                    if (!isTableUpdate) {
                        helperSrc.responseBody("", "ko", response, 500);
                    } else {
                        helperSrc.responseBody(JSON.stringify({ state: "ok", message: "User updated successfully." }), "", response, 200);
                    }
                }
            }
        });
    };
}
